### ISSUE TITLE
tc2_status error, due to company not having a `sales_person_id`

### ISSUE THREAD

**Issue by PrenSJ2** [tutorcruncher/hermes_v2#31]
Issue:
https://tutorcruncher.sentry.io/issues/4547995693/?project=4505607960264704&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=1

Believe Cause of Issue:
When a client is generating their kyc support link, for a company with no sales_person_id, we are unable to get the support person from `event.admin` as it might not exist - need to test

Proposed Solution:
check if `company.sales_person_id` and `event.admin`, if not use `/choose-roundrobin/support` to set the admin

**Comment by RaashiThakran** [comment]
<img width="367" alt="Screenshot_62" src="https://github.com/tutorcruncher/hermes_v2/assets/134603227/d6db2519-5be2-4577-887c-b17339856e33">

support link doesn't work unless I add myself as their sales person

**Comment by PrenSJ2** [comment]
patch 
query all companies with no sale id
if enterprise 
set to fionn
else set to sam
